### ISSUE TITLE
[Frontend] Add favicon and page title

### ISSUE THREAD

**Issue by AIFanatic** [AIFanatic/PaperLedger#39]
In GitLab by @nm on Jan 26, 2019, 19:20

null

**Comment by AIFanatic** [comment]
In GitLab by @nm on Jan 26, 2019, 19:20

changed title from **[Frontend] Add favico** to **[Frontend] Add favico{+n+}**

**Comment by AIFanatic** [comment]
In GitLab by @nm on Jan 26, 2019, 19:20

changed title from **[Frontend] Add favicon** to **[Frontend] Add favicon{+ and page title+}**

**Comment by BitcoinMitchell** [comment]
I've already added a small favicon in #3, but you might to create a better one. :stuck_out_tongue_winking_eye:
