### ISSUE TITLE
[Connectivity] Device goes to Welcome screen after a while and gets stuck

### ISSUE THREAD

**Issue by AIFanatic** [AIFanatic/PaperLedger#51]
Issue reported from DaveF:
https://bitcointalk.org/index.php?topic=5113453.msg50687270#msg50687270
>@DaveF
> Having an odd issue every now and then. The ledger will go to the connecting to internet screen and stay there. None of the buttons work when this happens. A 1 second pull of the USB cable and plugging it back in and it's good to go. 
> 
> Is anyone else seeing this?
> 
> -Dave

Member StackGambler confirmed the issue:
>@StackGambler
> Same here. Pretty minor issue, but annoying when it happens.

**Comment by BitcoinMitchell** [comment]
I haven't had this happen to me yet. Will keep an eye on it though.

**Comment by AIFanatic** [comment]
It seems that by flashing the development branch firmware the issue disappeared, closing.
